server:
  port: 8080
  error:
    include-message: always

spring:
  jackson:
    time-zone: Europe/Zagreb
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/asss_management
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  main:
    web-application-type: servlet

