package com.asss.management.entity.Enums;

public enum Type_of_event {
    EXAM_PERIOD,
    EXTRA_EXAM_PERIOD,
    ENROLLMENT_PERIOD,
    EXAM_REGISTRATION,
    EXAM_REGISTRATION_LATE,
    FIRST_SEMESTER,
    SECOND_SEMESTER,
    FYS_EXAM_REGISTRATION,
    FYS_EXAM_PERIOD
}
